spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/family_cloud
    username: postgres
    password: strongpassword
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.ethangeorlette.com/realms/family-cloud
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update # dev only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
keycloak:
  server-url: https://auth.ethangeorlette.com
  realm: family-cloud
  admin-client-id: family-cloud-backend
  admin-client-secret: Jry7G5zFlvnETic4e1LYODUSVPhVP9SK
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: files
server:
  port: 8080
