services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - cloud-network
    ports:
      - "5432:5432"
    depends_on:
      - keycloak

volumes:
  postgres-data:

networks:
  cloud-network:
    external: true
