version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_PROXY: "edge"
      KC_HOSTNAME: "https://auth.ethangeorlette.com"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"

    networks:
      - cloud-network
    ports:
      - "8180:8080"

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.keycloak.rule=Host(`auth.ethangeorlette.com`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"

      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

networks:
  cloud-network:
    external: true
